# -*- coding: utf-8 -*-
# vim: ft=yaml
---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit]
exclude: "^CHANGELOG.md$"
repos:
  # commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: detect-private-key
        name: "check for detected private key"
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        name: "fix trailing whitespace"
      - id: mixed-line-ending
        args: [--fix=lf]
        name: "fix line ending (lf)"
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: forbid-tabs
        name: "check forbidden tabs"
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      - id: shellcheck
        name: check shell scripts with shellcheck
        files: ^.*\.(sh|bash|ksh)$
        types: []
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.27.1
    hooks:
      - id: yamllint
        name: check YAML syntax with yamllint
        args: [--strict, "."]
        always_run: true
        pass_filenames: false
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.7
    hooks:
      - id: pymarkdown
        name: check Markdown files using pymarkdown
        files: \.(md|markdown)$
  - repo: https://github.com/oxsecurity/megalinter
    rev: v5.12.0 # Git tag specifying the hook, not mega-linter-runner, version
    hooks:
      - id: megalinter # Faster, less thorough, runs pre-commit by default
      - id: megalinter-all # Slower, more thorough, runs pre-push by default
  # commit-msg
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        name: check commit message using commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
